CUDA_VISIBLE_DEVICES=0 /home/lsy/.conda/envs/panda_rl/bin/python -u evaluate/evaluate_with_video.py \
  --exp-dir outputs/insert_posealign_noher_residual_seed1 \
  --model-name best_model \
  --episodes 50 \
  --seed-start 0 \
  --env FrankaPickAndPlaceWindowInsertSparse-v0 \
  --task-progress-features \
  --residual-guidance \
  --expert-hint-style insert \
  --residual-action-scale 0.015 \
  --no-vecnormalize \
  --no-stop-on-success \
  --max-steps 250 \
  --device cuda